title = "Elon Musk Tells Trump the Story of Landing on Mars"
description = "Elon Musk sits down with Donald Trump to share the hilarious story of SpaceX's successful landing on Mars."
global_image_style = "photograph, in a futuristic space station"
bgm_category = "comedy"
[[characters]]
name = "Donald Trump"
default_image_prompt = "Donald Trump with his signature hairstyle, wearing a suit"
voice_token = "TM:aejrk66wq3ss"

[[characters]]
name = "Elon Musk"
default_image_prompt = "Elon Musk with a big smile, wearing a SpaceX t-shirt"
voice_token = "TM:0vckhrxztgcw"

[[lines]]
character = "Elon Musk"
speech = "So, Mr. President, let me tell you the story of how we landed our rocket on Mars!"
image_prompt = "Elon Musk holding a little model of Mars, pretending to fly like a rocket"

[[lines]]
character = "Donald Trump"
speech = "I'm all ears, Elon. Impress me!"
image_prompt = "Donald Trump sitting with crossed arms, looking skeptical"

[[lines]]
character = "Elon Musk"
speech = "Well, it all started when our rocket blasted off from Earth, carrying precious cargo."
image_prompt = "Elon Musk standing in front of a SpaceX rocket, pointing towards the sky"

[[lines]]
character = "Donald Trump"
speech = "And what was in that precious cargo, Elon?"
image_prompt = "Donald Trump raising an eyebrow, looking curious"

[[lines]]
character = "Elon Musk"
speech = "A secret stash of... Cheetos!"
image_prompt = "Elon Musk holding a bag of Cheetos, looking mischievous"

[[lines]]
character = "Donald Trump"
speech = "Cheetos?! You've got to be kidding me!"
image_prompt = "Donald Trump with a shocked expression, holding his hand to his chest"

[[lines]]
character = "Elon Musk"
speech = "No, Mr. President, I'm dead serious. We wanted to make sure Mars feels like home!"
image_prompt = "Elon Musk wearing a funny Martian hat, holding a sign that says 'Welcome to Mars!'"

[[lines]]
character = "Donald Trump"
speech = "This is the most ridiculous thing I've ever heard, Elon."
image_prompt = "Donald Trump shaking his head, looking unimpressed"

[[lines]]
character = "Elon Musk"
speech = "But wait, there's more! The landing was so smooth, it felt like we were dancing on Mars!"
image_prompt = "Elon Musk doing a funny dance move, with a green Martian background"

[[lines]]
character = "Donald Trump"
speech = "Dancing on Mars? Now I've heard it all!"
image_prompt = "Donald Trump laughing with his hand on his stomach, finding it amusing"

[[lines]]
character = "Elon Musk"
speech = "Imagine the first Martians grooving to 'Uptown Funk'!"
image_prompt = "Elon Musk holding a boombox with 'Uptown Funk' written on it, with Martians around him"

[[lines]]
character = "Donald Trump"
speech = "Alright, Elon, you've got quite the imagination!"
image_prompt = "Donald Trump with a smirk, nodding in amusement"

[[lines]]
character = "Elon Musk"
speech = "Thank you, Mr. President. It was an out-of-this-world mission!"
image_prompt = "Elon Musk giving a thumbs up, with Earth and Mars in the background"

[[lines]]
character = "Donald Trump"
speech = "Well, Elon, I must say, this story was truly entertaining!"
image_prompt = "Donald Trump with an amused look, clapping his hands"

[[lines]]
character = "Elon Musk"
speech = "Glad you enjoyed it, Mr. President. Mars is waiting for us!"
image_prompt = "Elon Musk pointing towards Mars with excitement, ready for the next mission"

